services:
  # Base de datos SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: banco-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - banco-network

  # API .NET
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banco-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BancoSanabria;User Id=sa;Password=YourStrong@Password;TrustServerCertificate=True;
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - banco-network

volumes:
  sqlserver_data:

networks:
  banco-network:
    driver: bridge

